# 订阅链接

- type: webfuzzsub
  options:
    url: https://raw.githubusercontent.com/oouxx/fqsub/master/sub.list
- type: webfuzzsub
  options:
    url: https://github.com/doudoubinga/ceshi/blob/master/config/sub.list
    
    
    



# 订阅链接

- type: subscribe
  options:
    url: https://gooii.ml/v2ray/sub/vmess.html

# 网页模糊
- type: webfuzz
  options:
    url: https://merlinblog.xyz/wiki/freess.html


# tg

- type: tgchannel
  options:
    channel: NetfreexSrV
    num: 200
- type: tgchannel
  options:
    channel: vmesssr
    num: 200

# 论坛
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum-48-1.html

# 网站抓取
- type: https://free-ssr.xyz/
  options:
- type: subscribe
  options:
    url: https://pp.xbin.xyz/vmess/sub







  
  
  
