
# port of HTTP
port: 7890

# port of SOCKS5
socks-port: 7891

# (HTTP and SOCKS5 in one port)
# mixed-port: 7890

# redir port for Linux and macOS
# redir-port: 7892

allow-lan: false
mode: rule
log-level: info
external-controller: 127.0.0.1:9090

proxies:



proxy-groups:
  - name: 全局选择
    type: select
    proxies:
      - 负载均衡
      - 延迟最低
      - 手选本地
      - 手选延迟
      - 手选云1
      - 手选云2
      - 手选云3
      - 手选云4
      - 手选云5
      - 手选云6
      - 手选云7
      - 手选云8
      - 手选云9
      - 手选云10
      - 手选云11
      - 手选云12


  - name: 负载均衡
    type: load-balance
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    proxies:
      - 筛选1
      - 筛选2
      - 筛选3
      - 筛选4
      - 筛选5
      - 筛选6
      - 筛选7
      - 筛选8
      - 筛选9
      - 筛选10
      - 筛选11
      - 筛选13
      - 本地
      
  - name: 延迟最低
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    proxies:
      - 筛选1
      - 筛选2
      - 筛选3
      - 筛选4
      - 筛选5
      - 筛选6
      - 筛选7
      - 筛选8
      - 筛选9
      - 筛选10
      - 筛选11
      - 筛选13
      - 本地
  - name: 手选本地
    type: select
    proxies:
      - 本地
  - name: 手选延迟
    type: select
    proxies:
      - 筛选1
      - 筛选2
      - 筛选3
      - 筛选4
      - 筛选5
      - 筛选6
      - 筛选7
      - 筛选8
      - 筛选9
      - 筛选10
      - 筛选11
      - 筛选13
      - 本地
 
  - name: 手选云1
    type: select
    use:
      - websub1
  - name: 手选云2
    type: select
    use:
      - websub2
  - name: 手选云3
    type: select
    use:
      - websub3
  - name: 手选云4
    type: select
    use:
      - websub4
  - name: 手选云5
    type: select
    use:
      - websub5
  - name: 手选云6
    type: select
    use:
      - websub6
  - name: 手选云7
    type: select
    use:
      - websub7
  - name: 手选云8
    type: select
    use:
      - websub8
  - name: 手选云9
    type: select
    use:
      - websub9
  - name: 手选云10
    type: select
    use:
      - websub10
  - name: 手选云11
    type: select
    use:
      - websub11
  - name: 手选云12
    type: select
    use:
      - websub13






    


  - name: 筛选1
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 120
    use:
      - websub1

  - name: 筛选2
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 120
    use:
      - websub2
  - name: 筛选3
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 120
    use:
      - websub3
  - name: 筛选4
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 120
    use:
      - websub4
  - name: 筛选5
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 120
    use:
      - websub5
  - name: 筛选6
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 120
    use:
      - websub6
  - name: 筛选7
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 120
    use:
      - websub7
  - name: 筛选8
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 120
    use:
      - websub8
  - name: 筛选9
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 120
    use:
      - websub9
  - name: 筛选10
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 120
    use:
      - websub10
  - name: 筛选11
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 120
    use:
      - websub11

  - name: 筛选13
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 120
    use:
      - websub13
  - name: 本地
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 120
    use:
      - test


proxy-providers:
  websub:
    type: http
    url: "https://{{ .domain }}/clash/proxies"
    interval: 86400
    path: ./websub.yaml
    health-check:
      enable: true
      interval: 60
      url: http://www.gstatic.com/generate_204

  websub1:
    type: http
    url: "https://{{ .domain }}/clash/proxies?c=AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR,BS,BT,BU,BV,BW,BX,BY,BZ"
    interval: 86400
    path: ./websub1.yaml
    health-check:
      enable: true
      interval: 60
      url: http://www.gstatic.com/generate_204

  websub2:
    type: http
    url: "https://{{ .domain }}/clash/proxies?c=CA,CB,CC,CD,CE,CF,CG,CH,CI,CJ,CK,CL,CM,CN,CO,CP,CQ,CR,CS,CT,CU,CV,CW,CX,CY,CZ,DA,DB,DC,DD,DE,DF,DG,DH,DI,DJ,DK,DL,DM,DN,DO,DP,DQ,DR,DS,DT,DU,DV,DW,DX,DY,DZ"
    interval: 86400
    path: ./websub2.yaml
    health-check:
      enable: true
      interval: 60
      url: http://www.gstatic.com/generate_204

  websub3:
    type: http
    url: "https://{{ .domain }}/clash/proxies?c=EA,EB,EC,ED,EE,EF,EG,EH,EI,EJ,EK,EL,EM,EN,EO,EP,EQ,ER,ES,ET,EU,EV,EW,EX,EY,EZ,FA,FB,FC,FD,FE,FF,FG,FH,FI,FJ,FK,FL,FM,FN,FO,FP,FQ,FR,FS,FT,FU,FV,FW,FX,FY,FZ"
    interval: 86400
    path: ./websub3.yaml
    health-check:
      enable: true
      interval: 60
      url: http://www.gstatic.com/generate_204

  websub4:
    type: http
    url: "https://{{ .domain }}/clash/proxies?c=GA,GB,GC,GD,GE,GF,GG,GH,GI,GJ,GK,GL,GM,GN,GO,GP,GQ,GR,GS,GT,GU,GV,GW,GX,GY,GZ,HA,HB,HC,HD,HE,HF,HG,HH,HI,HJ,HK,HL,HM,HN,HO,HP,HQ,HR,HS,HT,HU,HV,HW,HX,HY,HZ"
    interval: 86400
    path: ./websub4.yaml
    health-check:
      enable: true
      interval: 60
      url: http://www.gstatic.com/generate_204

  websub5:
    type: http
    url: "https://{{ .domain }}/clash/proxies?c=IA,IB,IC,ID,IE,IF,IG,IH,II,IJ,IK,IL,IM,IN,IO,IP,IQ,IR,IS,IT,IU,IV,IW,IX,IY,IZ,JA,JB,JC,JD,JE,JF,JG,JH,JI,JJ,JK,JL,JM,JN,JO,JP,JQ,JR,JS,JT,JU,JV,JW,JX,JY,JZ"
    interval: 86400
    path: ./websub5.yaml
    health-check:
      enable: true
      interval: 60
      url: http://www.gstatic.com/generate_204

  websub6:
    type: http
    url: "https://{{ .domain }}/clash/proxies?c=KA,KB,KC,KD,KE,KF,KG,KH,KI,KJ,KK,KL,KM,KN,KO,KP,KQ,KR,KS,KT,KU,KV,KW,KX,KY,KZ,LA,LB,LC,LD,LE,LF,LG,LH,LI,LJ,LK,LL,LM,LN,LO,LP,LQ,LR,LS,LT,LU,LV,LW,LX,LY,LZ"
    interval: 86400
    path: ./websub6.yaml
    health-check:
      enable: true
      interval: 60
      url: http://www.gstatic.com/generate_204

  websub7:
    type: http
    url: "https://{{ .domain }}/clash/proxies?c=MA,MB,MC,MD,ME,MF,MG,MH,MI,MJ,MK,ML,MM,MN,MO,MP,MQ,MR,MS,MT,MU,MV,MW,MX,MY,MZ,NA,NB,NC,ND,NE,NF,NG,NH,NI,NJ,NK,NL,NM,NN,NO,NP,NQ,NR,NS,NT,NU,NV,NW,NX,NY,NZ"
    interval: 86400
    path: ./websub7.yaml
    health-check:
      enable: true
      interval: 60
      url: http://www.gstatic.com/generate_204

  websub8:
    type: http
    url: "https://{{ .domain }}/clash/proxies?c=OA,OB,OC,OD,OE,OF,OG,OH,OI,OJ,OK,OL,OM,ON,OO,OP,OQ,OR,OS,OT,OU,OV,OW,OX,OY,OZ,PA,PB,PC,PD,PE,PF,PG,PH,PI,PJ,PK,PL,PM,PN,PO,PP,PQ,PR,PS,PT,PU,PV,PW,PX,PY,PZ"
    interval: 86400
    path: ./websub8.yaml
    health-check:
      enable: true
      interval: 60
      url: http://www.gstatic.com/generate_204

  websub9:
    type: http
    url: "https://{{ .domain }}/clash/proxies?c=QA,QB,QC,QD,QE,QF,QG,QH,QI,QJ,QK,QL,QM,QN,QO,QP,QQ,QR,QS,QT,QU,QV,QW,QX,QY,QZ,RA,RB,RC,RD,RE,RF,RG,RH,RI,RJ,RK,RL,RM,RN,RO,RP,RQ,RR,RS,RT,RU,RV,RW,RX,RY,RZ"
    interval: 86400
    path: ./websub9.yaml
    health-check:
      enable: true
      interval: 60
      url: http://www.gstatic.com/generate_204

  websub10:
    type: http
    url: "https://{{ .domain }}/clash/proxies?c=SA,SB,SC,SD,SE,SF,SG,SH,SI,SJ,SK,SL,SM,SN,SO,SP,SQ,SR,SS,ST,SU,SV,SW,SX,SY,SZ,TA,TB,TC,TD,TE,TF,TG,TH,TI,TJ,TK,TL,TM,TN,TO,TP,TQ,TR,TS,TT,TU,TV,TW,TX,TY,TZ"
    interval: 86400
    path: ./websub10.yaml
    health-check:
      enable: true
      interval: 60
      url: http://www.gstatic.com/generate_204

  websub11:
    type: http
    url: "https://{{ .domain }}/clash/proxies?c=UA,UB,UC,UD,UE,UF,UG,UH,UI,UJ,UK,UL,UM,UN,UO,UP,UQ,UR,US,UT,UU,UV,UW,UX,UY,UZ,VA,VB,VC,VD,VE,VF,VG,VH,VI,VJ,VK,VL,VM,VN,VO,VP,VQ,VR,VS,VT,VU,VV,VW,VX,VY,VZ"
    interval: 86400
    path: ./websub11.yaml
    health-check:
      enable: true
      interval: 60
      url: http://www.gstatic.com/generate_204



  websub13:
    type: http
    url: "https://{{ .domain }}/clash/proxies?c=YA,YB,YC,YD,YE,YF,YG,YH,YI,YJ,YK,YL,YM,YN,YO,YP,YQ,YR,YS,YT,YU,YV,YW,YX,YY,YZ,ZA,ZB,ZC,ZD,ZE,ZF,ZG,ZH,ZI,ZJ,ZK,ZL,ZM,ZN,ZO,ZP,ZQ,ZR,ZS,ZT,ZU,ZV,ZW,ZX,ZY,ZZ"
    interval: 86400
    path: ./websub13.yaml
    health-check:
      enable: true
      interval: 60
      url: http://www.gstatic.com/generate_204
  test:
    type: file
    path: ./test.yaml
    health-check:
      enable: true
      interval: 60
      url: http://www.gstatic.com/generate_204
rules:
  - DOMAIN-SUFFIX,smtp,DIRECT
  - DOMAIN-KEYWORD,aria2,DIRECT

  - GEOIP,CN,DIRECT

  - MATCH,全局选择

